version: "3.5"
# You should be able to find & replace all instances of farmbot with 
# your actual_service_name. Then you just need address any places that 
# typically need changes (designated by comments)

networks:
  farmbot:
  farmbot-private:

volumes:
  farmbot:
  farmbot-db:

secrets:
  farmbot_admin_password:
    name: ${STACK_NAME:-technocore}_farmbot_admin_password
    external: true
  farmbot_farmbot_db_password:
    name: ${STACK_NAME:-technocore}_farmbot_farmbot_db_password
    external: true
  farmbot_db_farmbot_password:
    name: ${STACK_NAME:-technocore}_farmbot_db_farmbot_password
    external: true

services:
  # Uncomment this if Traefik will be used for routing traffick to this service.
  ingress:
    networks:
      - farmbot

  farmbot:
    deploy:
      labels:
        - traefik.frontend.rule=$FARMBOT_ROUTING_LABEL
        - traefik.frontend.priority=$FARMBOT_ROUTING_LABEL_PRIORITY
        # You'll need to set applicaiton's port here.
        - traefik.port=3000
        - ${TRAEFIK_BASIC_AUTH}
        - traefik.enable=true
        - traefik.tags=ingress 
        - traefik.docker.network=${STACK_NAME:-technocore}_farmbot
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
      #placement:
      #  constraints:
      #    - node.role == manager
      # Big services will need this modified or removed.
      #resources:
      #  limits:
      #    memory: 128M
      #  reservations:
      #    memory: 64M
    environment:
      #- MQTT_USER=${farmbot}
      - POSTGRES_PASSWORD={{"{{DOCKER-SECRET:farmbot_db_password}}"}}
      - ADMIN_USER=${ADMIN_USER}
      - API_HOST=farmbot.${DOMAIN}
      - API_PORT=443
      - MQTT_HOST=mqtt
      - REDIS_URL=redis://farmbot_redis:6379/0

    image: ${image_provider:-scififarms}/technocore-farmbot:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - farmbot
      - farmbot-private
    secrets:
      - source: farmbot_farmbot_db_password
        target: farmbot_db_password
      - source: farmbot_admin_password
        target: admin_password
    volumes:
      # Might need to delete farmbot volume.
      #- farmbot:/farmbot
      - ${DEV_MOUNT_FARMBOT_SHELL_MIGRATIONS:-$EMPTY_MOUNT}

  farmbot_redis:
    deploy:
      labels:
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
    image: redis:5-alpine
    networks:
      - farmbot-private

  farmbot_db:
    deploy:
      labels:
        - com.ouroboros.enable=true
      mode: global
      restart_policy:
        condition: any
    environment:
      - POSTGRES_USER=farmbot
      - POSTGRES_PASSWORD={{"{{DOCKER-SECRET:farmbot_password}}"}}
      - POSTGRES_DB=farmbot
    image: ${image_provider:-scififarms}/technocore-farmbot-db:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - farmbot-private
    secrets:
      - source: farmbot_db_farmbot_password
        target: farmbot_password
    volumes:
      - farmbot-db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
